## Create tables in database

In [22]:
import sqlite3

In [40]:
conn = sqlite3.connect('../Board-Game-Data/board_game_database.db')
cursor = conn.cursor()

cursor.execute('''
        CREATE TABLE сountries (
        country_id INTEGER PRIMARY KEY,
        country TEXT
        )
''')

cursor.execute('''
        CREATE TABLE states (
        state_id INTEGER PRIMARY KEY,
        state TEXT NOT NULL
        )
''')

cursor.execute('''
        CREATE TABLE cities (
        city_id INTEGER PRIMARY KEY,
        city TEXT NOT NULL
        )
''')

cursor.execute('''
        CREATE TABLE users (
        user_id INTEGER PRIMARY KEY,
        nickname TEXT NOT NULL,
        country_id INTEGER REFERENCES сountries(country_id),
        state_id INTEGER REFERENCES states(state_id),
        city_id INTEGER REFERENCES cities(city_id),
        last_check DATE DEFAULT CURRENT_DATE NOT NULL
        )
''')

cursor.execute('''
        CREATE TABLE links (
        link_id INTEGER PRIMARY KEY,
        link TEXT NOT NULL
        )
''')

cursor.execute('''
        CREATE TABLE publishers (
        publisher_id INTEGER PRIMARY KEY,
        publisher TEXT NOT NULL
        )
''')

cursor.execute('''
        CREATE TABLE boardgames (
        boardgame_id INTEGER PRIMARY KEY,
        title TEXT NOT NULL,
        year_published INTEGER,
        min_players INTEGER,
        max_players INTEGER,
        min_playtime INTEGER,
        max_playtime INTEGER,
        age INTEGER,
        users_rated INTEGER,
        average_rating FLOAT,
        bayes_average_rating FLOAT,
        std_dev FLOAT,
        owned INTEGER,
        trading INTEGER,
        wishing INTEGER,
        num_of_comments INTEGER,
        num_of_weights INTEGER,
        average_weight FLOAT,
        main_publisher_id INTEGER REFERENCES publishers(publisher_id),
        thumbnail_link_id INTEGER REFERENCES links(link_id),
        image_link_id INTEGER REFERENCES links(link_id),
        last_check DATE DEFAULT CURRENT_DATE NOT NULL
    );
''')

cursor.execute('''
        CREATE TABLE comments (
        comment_id INTEGER PRIMARY KEY,
        comment TEXT NOT NULL
        )
''')

cursor.execute('''
        CREATE TABLE ratings (
        user_id INTEGER REFERENCES users(user_id),
        boardgame_id INTEGER REFERENCES boardgames(boardgame_id),
        rating FLOAT NOT NULL,
        num_of_plays INTEGER NOT NULL,
        comment_id INTEGER REFERENCES comments(comment_id),
        own BOOLEAN NOT NULL,
        prevowned BOOLEAN NOT NULL,
        for_trade BOOLEAN NOT NULL,
        want BOOLEAN NOT NULL,
        want_to_play BOOLEAN NOT NULL,
        want_to_buy BOOLEAN NOT NULL,
        wishlist BOOLEAN NOT NULL,
        preordered BOOLEAN NOT NULL,
        last_modified DATE NOT NULL,
        PRIMARY KEY (user_id, boardgame_id)
        );
''')

cursor.execute('''
        CREATE TABLE descriptions (
        boardgame_id INTEGER PRIMARY KEY REFERENCES boardgames(boardgame_id),
        description TEXT NOT NULL
        )
''')

cursor.execute('''
        CREATE TABLE boardgame_publishers (
        boardgame_id INTEGER REFERENCES boardgames(boardgame_id),
        publisher_id INTEGER REFERENCES publishers(publisher_id),
        PRIMARY KEY (boardgame_id, publisher_id)
        )
''')

cursor.execute('''
        CREATE TABLE honors (
        honor_id INTEGER PRIMARY KEY,
        honor TEXT NOT NULL
        )
''')

cursor.execute('''
        CREATE TABLE boardgame_honors (
        boardgame_id INTEGER REFERENCES boardgames(boardgame_id),
        honor_id INTEGER REFERENCES honors(honor_id),
        PRIMARY KEY (boardgame_id, honor_id)
        )
''')

cursor.execute('''
        CREATE TABLE expansions (
        expansion_id INTEGER PRIMARY KEY,
        expansion TEXT NOT NULL
        )
''')

cursor.execute('''
        CREATE TABLE boardgame_expansions (
        boardgame_id INTEGER REFERENCES boardgames(boardgame_id),
        expansion_id INTEGER REFERENCES expansions(expansion_id),
        PRIMARY KEY (boardgame_id, expansion_id)
        )
''')

cursor.execute('''
        CREATE TABLE accessories (
        accessory_id INTEGER PRIMARY KEY,
        accessory TEXT NOT NULL
        )
''')

cursor.execute('''
        CREATE TABLE boardgame_accessories (
        boardgame_id INTEGER REFERENCES boardgames(boardgame_id),
        accessory_id INTEGER REFERENCES accessories(accessory_id),
        PRIMARY KEY (boardgame_id, accessory_id)
        )
''')

cursor.execute('''
        CREATE TABLE persons (
        person_id INTEGER PRIMARY KEY,
        name TEXT NOT NULL
        )
''')

cursor.execute('''
        CREATE TABLE boardgame_artists (
        boardgame_id INTEGER REFERENCES boardgames(boardgame_id),
        artist_id INTEGER REFERENCES persons(person_id),
        PRIMARY KEY (boardgame_id, artist_id)
        )
''')

cursor.execute('''
        CREATE TABLE mechanics (
        mechanic_id INTEGER PRIMARY KEY,
        mechanic TEXT NOT NULL
        )
''')

cursor.execute('''
        CREATE TABLE boardgame_mechanics (
        boardgame_id INTEGER REFERENCES boardgames(boardgame_id),
        mechanic_id INTEGER REFERENCES mechanics(mechanic_id),
        PRIMARY KEY (boardgame_id, mechanic_id)
        )
''')

cursor.execute('''
        CREATE TABLE categories (
        category_id INTEGER PRIMARY KEY,
        category TEXT NOT NULL
        )
''')

cursor.execute('''
        CREATE TABLE boardgame_categories (
        boardgame_id INTEGER REFERENCES boardgames(boardgame_id),
        category_id INTEGER REFERENCES categories(category_id),
        PRIMARY KEY (boardgame_id, category_id)
        )
''')

cursor.execute('''
        CREATE TABLE boardgame_designers (
        boardgame_id INTEGER REFERENCES boardgames(boardgame_id),
        designer_id INTEGER REFERENCES persons(person_id),
        PRIMARY KEY (boardgame_id, designer_id)
        )
''')

cursor.execute('''
        CREATE TABLE boardgame_graphic_designers (
        boardgame_id INTEGER REFERENCES boardgames(boardgame_id),
        graphic_designer_id INTEGER REFERENCES persons(person_id),
        PRIMARY KEY (boardgame_id, graphic_designer_id)
        )
''')

cursor.execute('''
        CREATE TABLE subdomains (
        boardgame_id INTEGER PRIMARY KEY REFERENCES boardgames(boardgame_id),
        wargames BOOLEAN DEFAULT 0,
        abstract BOOLEAN DEFAULT 0,
        party BOOLEAN DEFAULT 0,
        childrens BOOLEAN DEFAULT 0,
        thematic BOOLEAN DEFAULT 0,
        customizable BOOLEAN DEFAULT 0,
        family BOOLEAN DEFAULT 0,
        strategy BOOLEAN DEFAULT 0
        )
''')

cursor.execute('''
        CREATE TABLE implementations (
        major_boardgame_id INTEGER REFERENCES boardgames(boardgame_id),
        minor_boardgame_id INTEGER REFERENCES boardgames(boardgame_id),
        PRIMARY KEY (major_boardgame_id, minor_boardgame_id)
        )
''')

cursor.execute('''
        CREATE TABLE podcast_episodes (
        podcast_episode_id INTEGER PRIMARY KEY,
        podcast_episode TEXT NOT NULL
        )
''')

cursor.execute('''
        CREATE TABLE boardgame_podcast_episodes (
        boardgame_id INTEGER REFERENCES boardgames(boardgame_id),
        podcast_episode_id INTEGER REFERENCES podcast_episodes(podcast_episode_id),
        PRIMARY KEY (boardgame_id, podcast_episode_id)
        )
''')

cursor.execute('''
        CREATE TABLE sales (
        sale_id INTEGER PRIMARY KEY,
        unix_saledate INTEGER NOT NULL,
        saletime INTEGER NOT NULL,
        price FLOAT NOT NULL,
        currency CHAR(3) NOT NULL,
        condition TEXT NOT NULL
        )
''')

cursor.execute('''
        CREATE TABLE boardgame_sales (
        boardgame_id INTEGER REFERENCES boardgames(boardgame_id),
        sale_id INTEGER REFERENCES sales(sale_id),
        PRIMARY KEY (boardgame_id, sale_id)
        )
''')

cursor.execute('''
        CREATE TABLE ranks (
        boardgame_id INTEGER PRIMARY KEY,
        bgg_rank INTEGER,
        customizable_rank INTEGER,
        atari_st_rank INTEGER,
        rpg_item_rank INTEGER,
        arcade_rank INTEGER,
        strategy_game_rank INTEGER,
        childrens_game_rank INTEGER,
        family_game_rank INTEGER,
        abstract_game_rank INTEGER,
        board_game_issue_rank INTEGER,
        party_game_rank INTEGER,
        thematic_rank INTEGER,
        commodore_64_rank INTEGER,
        accessory_rank INTEGER,
        amiga_rank INTEGER,
        wargame_rank INTEGER,
        videogame_rank INTEGER
        )
''')

conn.commit()
conn.close()

## Check tables in database

In [41]:
# create a connection to the database
conn = sqlite3.connect('../Board-Game-Data/board_game_database.db')

# create a cursor object
cursor = conn.cursor()

# execute a SELECT statement to get the list of tables in the database
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")

# fetch the results and store them in a list
tables = cursor.fetchall()

# print the list of table names
print(tables)

# close the connection
conn.close()

[('сountries',), ('states',), ('cities',), ('users',), ('links',), ('publishers',), ('boardgames',), ('comments',), ('ratings',), ('descriptions',), ('boardgame_publishers',), ('honors',), ('boardgame_honors',), ('expansions',), ('boardgame_expansions',), ('accessories',), ('boardgame_accessories',), ('persons',), ('boardgame_artists',), ('mechanics',), ('boardgame_mechanics',), ('categories',), ('boardgame_categories',), ('boardgame_designers',), ('boardgame_graphic_designers',), ('subdomains',), ('implementations',), ('podcast_episodes',), ('boardgame_podcast_episodes',), ('sales',), ('boardgame_sales',), ('ranks',)]

In [42]:
import sqlite3

# Connect to the database
conn = sqlite3.connect('../Board-Game-Data/board_game_database.db')

# Get a cursor object
cursor = conn.cursor()

# Execute the PRAGMA statement to get the table schema
cursor.execute("PRAGMA table_info(users)")

# Fetch all the rows returned by the statement
rows = cursor.fetchall()

# Print the table schema
for row in rows:
    print(row)

# Close the cursor and the database connection
cursor.close()
conn.close()

(0, 'user_id', 'INTEGER', 0, None, 1)
(1, 'nickname', 'TEXT', 1, None, 0)
(2, 'country_id', 'INTEGER', 0, None, 0)
(3, 'state_id', 'INTEGER', 0, None, 0)
(4, 'city_id', 'INTEGER', 0, None, 0)
(5, 'last_check', 'DATE', 1, 'CURRENT_DATE', 0)